# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161001_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='posttype',
            unique_together=set([('type',)]),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.PostType'),
            preserve_default=False,
        ),
    ]
