# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161004_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro_test',
            field=models.CharField(default='', max_length=150),
        ),
    ]
